### ISSUE TITLE
Setting up community management

### ISSUE THREAD

**Issue by EKaroune** [open-phytoliths/FAIR-phytoliths#1]
We need to decide how we are going to run our project and need to get a number of tasks done.

Let's have a discussion about these issues and start to work on them.

- [x] Set up slack account for communication
- [x] Set up gmail account for organisation
- [x] Setting up repository as organisation with organisation user details
- [x] README file with vision statement, open canvas, roadmap, contact details.
- [x] Code of conduct
- [x] Contributor guidelines
- [x] Set up twitter
- [x] Set up webpage
- [x] Make an advertising slide to use at conferences. [Google slide](https://docs.google.com/presentation/d/1oKKvrTBxNDhOJ6JGdITTY9FMz1yaeqAd/edit#slide=id.p2)
- [x] Authorship guidelines
- [x] setting up all contributors bot
- [ ] adding contributors from funding and OLS3 
- [ ] Translation of readme in to spanish and other languages.

Add anything else to the list above that needs to be done.

**Comment by EKaroune** [comment]
We are keeping notes from our Open Life Science 3 project meetings [here](https://hackmd.io/mkI1GgoaTvKp8xELJhaNAQ)

This has a record of our discussions so far.

**Comment by EKaroune** [comment]
I've added a template to the readme in the branch -  testingbranch

**Comment by EKaroune** [comment]
we need to add contributors from our funding application:
* Dan Cabanes - I met with him to discuss the project = ideas
* Malvika Sharan - wrote letter of recommendation for funding application = funding

**Comment by jruizperez** [comment]
> We need to add contributors from our funding application:
> 
> * Dan Cabanes - I met with him to discuss the project = ideas
> * Malvika Sharan - wrote letter of recommendation for funding application = funding
> * Doris Barboni and Rand Evert
> * Gill Campbell - wrote letter of recommendation  for funding and other help with funding application/ facilitation of project at Historic England

**Comment by EKaroune** [comment]
@all-contributors add @dancabanes for ideas

**Comment by jruizperez** [comment]
@all-contributors add @m4bcn for doc, ideas, projectManagement

**Comment by jruizperez** [comment]
@all-contributors add @malvikasharan for fundingFinding

**Comment by EKaroune** [comment]
@all-contributors add @malvikasharan for fundingFinding

**Comment by EKaroune** [comment]
@all-contributors add @m4bcn for doc, ideas, projectManagement

**Comment by jruizperez** [comment]
@all-contributors add @francesca-dagostini for test

**Comment by EKaroune** [comment]
@all-contributors add @GCampbell10 for funding

**Comment by EKaroune** [comment]
@all-contributors add @GCampbell10 for fundingFinding

**Comment by EKaroune** [comment]
The rest of this will completed in EOSC project so a new issue has been started for these matters.
