### ISSUE TITLE
Writing data paper for FAIR assessment

### ISSUE THREAD

**Issue by EKaroune** [open-phytoliths/FAIR-phytoliths#38]
- [x] finalise dataset
- [x] clean dataset
- [x] upload dataset to repository
- [x] Select journal for data paper - Scientific data, JOAD, Open research europe, data in brief, botanical studie?
- [x] Write data paper
- [x] Edit data paper
- [x] submit data paper
- [x] do revisions from peer review

**Comment by Cel31** [comment]
I just ticked the actions we made such as cleaning and uploading the dataset to the repository

**Comment by EKaroune** [comment]
Thanks Celine

**Comment by Cel31** [comment]
Data paper revisions are all done
